spring.application.name=Catalogo
spring.datasource.url=jdbc:postgresql://localhost:5432/mystadium_catalogo
spring.datasource.username=postgres
spring.datasource.password=240800
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
app.images.path=F:/Esteban/Trabajos U/Semestre 8/Profundizaciones/E-Gestion de proyectos de software/Ecomerce/Ecomerce/MyStadium/Frontend/imagenes
