spring.application.name=Notifications
server.port=8083

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mystadium312@gmail.com
spring.mail.password=dnbcnygdiqttieex
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=mystadium312@gmail.com

server.mapa-calor.url=http://localhost:8084
server.catalogo.url=http://localhost:8082
app.images.base-path=F:/Esteban/Trabajos U/Semestre 8/Profundizaciones/E-Gestion de proyectos de software/Ecomerce/Ecomerce/MyStadium/Frontend/imagenes
